config/routes.rb
Rails.application.routes.draw do
  get "static_pages/about_us"
  get "static_pages/terms_of_service"
  get "static_pages/privacy_policy"
  devise_for :users
  root 'reports#index'
  resources :set_list_orders, only: [:create, :update, :destroy]
  resources :user_favorites, only: [:create, :destroy]
  resources :sections, only: [:create, :update, :destroy]
  resources :report_bodies, only: [:create, :update]
  resources :report_favorites, only: [:create, :destroy]
  resources :reports do
    resources :sections do
      resources :set_list_orders do
        member do
          patch :update_position
          get :edit
        end
      end
      patch 'update_song_order', on: :member
    end
    post 'create_new', on: :collection
    collection do
      get 'invitation'
    end  
    member do
      get 'add_song'
      post 'add_song'
    end
  end
  namespace :search do
    get 'suggest_artists'
    get 'suggest_tracks'
  end
  resources :songs, only: [:new, :create]
  resources :users
  namespace :user do
    resources :my_reports do
      member do
        patch :toggle_status
      end
    end
  end
  resources :concerts
  get 'search/index'
  get 'mypage', to: 'users#mypage', as: :mypage

  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  get "search", to: "search#index"
  get "search/suggest_artists"
  get "search/suggest_tracks"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  authenticates_with_sorcery!
  has_many :reports
  
  # ユーザーが他のユーザーをフォロー
  has_many :user_favorites
  has_many :favorited_users, through: :user_favorites, source: :favorited_user

  # ユーザーが他のユーザーにフォローされる
  has_many :inverse_user_favorites, class_name: "UserFavorite", foreign_key: "favorited_user_id"
  has_many :followers, through: :inverse_user_favorites, source: :user

  # レポートのイイネ
  has_many :report_favorites
  has_many :favorited_reports, through: :report_favorites, source: :report

  validates :email, uniqueness: true, presence: true
  validates :email, :email_format => {:message => '正しいメールアドレスを入力してください'}
  validates :password, presence: true 
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  end

app/controllers/user/my_reports_controller.rb
class User::MyReportsController < ApplicationController
    before_action :require_login
    
    def index
      @reports = case params[:status]
                when 'draft'
                    current_user.reports.drafts.joins(:concert).order('concerts.date DESC')
                when 'published'
                    current_user.reports.published.joins(:concert).order('concerts.date DESC')
                else
                    current_user.reports.published.joins(:concert).order('concerts.date DESC')
                end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:mypage]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      flash[:success] = "ユーザー登録が成功しました"
      redirect_to mypage_path
    else
      flash.now[:danger] = @user.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other
  end

  def mypage
    @user = current_user
  end

  def myreports
    @user = current_user
    @reports = current_user.reports.includes(:concert).order(created_at: :desc)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
users#create

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/mypage.html.erb
  <h1>マイページ</h1>
  <p class="head-text">キミレポへのご訪問ありがとうございます。</p>
  <p class="head-text">ここではご自身のレポートの振り返りと編集、プロフィール編集、フォローしたユーザーの管理、確認などができます。キミレポをぜひご活用ください。</p>
  <div class="mypage-div">
    <ul class="mypage-ul">
      <li class="mypage-li"><i class="fa-solid fa-file-lines fa-fw"></i><%= link_to "レポート管理", user_my_reports_path, method: :get %></li>
      <li class="mypage-li"><i class="fa-solid fa-user-pen fa-fw"></i><%= link_to "プロフィール編集", '#' %></li>
      <li class="mypage-li"><i class="fa-solid fa-user-check fa-fw"></i><%= link_to "イイネユーザー管理", '#' %></li>
      <li class="mypage-li"><i class="fa-solid fa-file-circle-check fa-fw"></i><%= link_to "イイネしたレポートを読む", '#' %></li>
    </ul>
  </div>
    <%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' %>

app/views/users/new.html.erb
<h1>新規登録画面</h1>
<%= form_with(model: @user, local: true, class: 'common-form') do |f| %>
    <div class="form-group">
        <p><%= f.label :name, 'ユーザー名（表示名）' %></p>
        <%= f.text_field :name %>
    </div>

    <div class="form-group">
        <p><%= f.label :email, 'メールアドレス' %></p>
        <%= f.email_field :email %>
    </div>

    <div class="form-group">
        <p><%= f.label :password, 'パスワード' %></p>
        <%= f.password_field :password %>
    </div>

    <div class="form-group">
        <p><%= f.label :password_confirmation, 'パスワード（確認）' %></p>
        <%= f.password_field :password_confirmation %>
    </div>

    <div class="form-group">
        <%= f.submit '新規登録', class: 'submit-button' %>
    </div>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>